#!/bin/bash

echo "Choose depending on need:"

PS3='Your Choice? '

options=("01" "02" "03")

select op in "${options[@]}"

do

sep="===============================";
admin1=$(echo $SUDO_USER);
  case $op in
                "01") clear; echo "Basic troubleshooting and details"
                      count=$(exim -bpc)
                      echo "queue count is $count";;
      #eximqsumm
      #Need to check what is the best course of action for acqiring details
      #about the volumes with the username
                "02") clear; echo "Indentfy malicious activity"
      #Check for crons  
                        exim -bp | awk '{print $5}' | cut -d '(' -f2 | cut -d ')' -f1 | sort | uniq -c |awk '$1 > 50' | sort -nk1 > /admin/$admin1/exim.text
      #crons
                        for i in $(cat /admin/$admin1/exim.text | awk '{print $2}'); do echo $sep; grep -R $i /var/spool/cron/;done
      #logs
                        cd /var/log; for i in $(ls | awk '/exim/ {print $0}' | grep -v gz ); do echo "$i"; cat $i | grep -oP "(?<=cwd=/home\d).*(?=:\s\/usr)" ;done > /admin/$admin1/mail_via_scripts.text
      #needs to check the output for the above command. ^^^
                        echo "List of users sending scripts for above 1000 count"; cat /admin/$admin1/mail_via_scripts.text |cut -d '/' -f2 | awk '{print $1}' | sort | uniq -c | sort -nk1 | awk '$1 > 1000'
                        ;;

               "03") clear; echo "Full exim report at /admin/$username/exm_report"

                echo "count is $count"
                echo $sep;
                echo "The basic report is as follows:"
                exim -bp | awk '{print $4"   "$5}' |sort |uniq -c | sort -nk1
                echo $sep;

                echo "Malicious behavior:"
                echo $sep;
                cat /admin/$admin1/mail_via_scripts.text |cut -d '/' -f2 | awk '{print $1}' | sort | uniq -c | sort -nk1 | awk '$1 > 1000';
                echo $sep;

                echo "Malicious cron in /var/spool/cron"
                echo $sep
                for i in $(cat /admin/$admin1/exim.text | awk '{print $2}'); do echo $sep; grep -R $i /var/spool/cron/;done
                echo $sep

                echo "Thank you for using!!!!"

        esac
done
